In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [6]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score

iris = pd.read_csv(r"C:\ThirdYear_Notes\Practicals\DSBDA\IRIS.csv")
Xir = iris.iloc[:,:4]
yir = iris['species']
nb = GaussianNB().fit(Xir, yir)
preds = nb.predict(Xir)
print("Confusion Matrix:\n", confusion_matrix(yir,preds))
print("Accuracy:", accuracy_score(yir,preds))


Confusion Matrix:
 [[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]
Accuracy: 0.96
